edgedb/cache/cache.go
I was doing some reading and this seems to the more idiomatic approach. It seems like channels are seen as communicating information not locking.
=> use mutext instead of channel

edgedb/protocol/codecs/codecs.go
=> ignore unknown descriptor types

edgedb.go, granular_flow.go, protocol/buff/reader.go, protocol/buff/reader_test.go, protocol/buff/writer.go, protocol/buff/writer_test.go, protocol/codecs/array.go, protocol/codecs/array_test.go, protocol/codecs/base_scalar.go, protocol/codecs/base_scalar_test.go, protocol/codecs/codecs.go, protocol/codecs/codecs_test.go, protocol/codecs/named_tuple.go, protocol/codecs/named_tuple_test.go, protocol/codecs/object.go, protocol/codecs/object_test.go, protocol/codecs/set.go, protocol/codecs/set_test.go, protocol/codecs/tuple.go, protocol/codecs/tuple_test.go, query_test.go
=> decode into unsafe.Pointer instead of reflect.Value

.github/workflows/tests.yml, main_test.go
fixes https://github.com/edgedb/edgedb-go/issues/38
=> migrate CI test setup to edgedb/setup-edgedb

edgedb.go, granular_flow.go, internal/codecs/base_scalar.go, internal/codecs/base_scalar_test.go, internal/codecs/codecs.go, internal/codecs/named_tuple.go, internal/codecs/named_tuple_test.go, internal/codecs/object.go, internal/codecs/tuple.go, pool.go, tutorial_test.go
All todo comments were either stale or an issue has been created.
=> remove todo comments

Makefile, conn.go, connutils.go, connutils_test.go, edgedb.go, error.go, generatederrors.go, internal/cmd/generr/errortype.go, internal/cmd/generr/main.go, internal/cmd/generr/tags.go, internal/codecs/tuple.go, options.go, pool.go
this feature is part of [RFC1004](https://github.com/edgedb/edgedb-go/issues/32)
=> add reconnect on retryable errors

cache.go, granular_flow.go, internal/buff/read.go, internal/buff/read_test.go, internal/buff/write.go, internal/buff/write_test.go, internal/codecs/array.go, internal/codecs/base_scalar.go, internal/codecs/base_scalar_test.go, internal/codecs/codecs.go, internal/codecs/named_tuple.go, internal/codecs/named_tuple_test.go, internal/codecs/object.go, internal/codecs/object_test.go, internal/codecs/set.go, internal/codecs/tuple.go, internal/codecs/tuple_test.go, internal/types/uuid.go, tutorial_test.go, uuid.go, uuid_test.go
fixes https://github.com/edgedb/edgedb-go/issues/57
fixes https://github.com/edgedb/edgedb-go/issues/25
=> remove types package

internal/codecs/tuple.go, internal/codecs/tuple_test.go
fixes https://github.com/edgedb/edgedb-go/issues/69
=> reject extra tuple elements

internal/buff/read.go, internal/soc/soc.go
fixes https://github.com/edgedb/edgedb-go/issues/60
=> set slice capacity with 3-index syntax

connect.go, fallthrough.go, granular_flow.go, internal/codecs/array.go, internal/codecs/object.go, internal/codecs/object_test.go, script_flow.go
fixes https://github.com/edgedb/edgedb-go/issues/42
fixes https://github.com/edgedb/edgedb-go/issues/40
=> assert predictable values in protocol data

edgedb.go, poolconn.go
fixes https://github.com/edgedb/edgedb-go/issues/39
=> close connection on unexpected message

granular_flow.go, internal/cardinality/cardinality.go, query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/36
=> assert cardinality 

edgedb.go, internal/codecs/base_scalar.go, internal/codecs/base_scalar_test.go, query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/49
=> update json codec

.github/workflows/tests.yml
fixes https://github.com/edgedb/edgedb-go/issues/26
=> run micro benchmarks in CI

edgedb.go, granular_flow.go, internal/buff/write.go, internal/buff/write_test.go, internal/codecs/base_scalar.go, internal/codecs/base_scalar_test.go, query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/50
=> add bigint codec

query_test.go
I was double checking that certain codecs were correct. It turns out they were, and I ended up with some new tests in the process of confirming. Seems worth while keeping them.
=> add datetime tests

internal/codecs/base_scalar.go, internal/codecs/datetime.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/datetime_test.go, query_test.go, types.go
working on https://github.com/edgedb/edgedb-go/issues/48
=> add cal::local_datetime codec

internal/codecs/base_scalar.go, internal/codecs/base_scalar_test.go, internal/codecs/datetime.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/datetime_test.go, query_test.go, types.go
fixes https://github.com/edgedb/edgedb-go/issues/88
=> add edgedb.Duration type

internal/codecs/base_scalar.go, internal/codecs/datetime.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/datetime_test.go, query_test.go, types.go
working on https://github.com/edgedb/edgedb-go/issues/48
=> add cal::local_date codec

internal/codecs/codecs.go, internal/codecs/scalar.go, main_test.go, query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/45
=> support the scalar type descriptor

internal/codecs/codecs.go, internal/codecs/enum.go, main_test.go, query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/46
=> add support for enum

edgedb.go, internal/codecs/base_scalar.go, internal/codecs/datetime.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/datetime_test.go, query_test.go, types.go
fixes https://github.com/edgedb/edgedb-go/issues/48
=> add cal::local_time codec

cache.go, connect.go, doc.go, edgedb.go, granular_flow.go, internal/header/header.go, pool.go, pool_test.go, poolconn_test.go, query.go, query_test.go, reconnect.go, script_flow.go, transaction.go
fixes https://github.com/edgedb/edgedb-go/issues/96
=> refuse transactions outside of TryTx & Retry

types_test.go
fixes https://github.com/edgedb/edgedb-go/issues/102
=> expand range of tested durations

internal/edgedbtypes/uuid.go, internal/edgedbtypes/uuid_test.go, types.go
Make it easy to get a UUID from a string.
=> add edgedb.ParseUUID

connect.go, edgedb.go, granularflow.go, internal/codecs/codecs.go, internal/codecs/nil.go, internal/codecs/noop.go, internal/descriptor/descriptor.go, internal/header/header.go, pool_test.go, query_test.go, scriptflow.go
fixes https://github.com/edgedb/edgedb-go/issues/124
=> set EXPLICIT_OBJECTIDS header

connutils.go
Details:
1. Uses current directory for project dir
2. Does not search of the ancestor directories (unlike CLI tool)
3. Now crashes if edgedb.toml not found and no parameters specified
Also includes implementation of EDGEDB_INSTANCE env var support
=> implement reading project config

connutils.go, darwin.go, go.mod, go.sum, windows.go
Use `edgedb self migrate` to migrate the old dir to the new location.
=> Use system config dir instead of ~/.edgedb

README.md
Fix `go get` code so it's copypastable.
=> Fix go get command

internal/codecs/object.go, types_test.go
fixes https://github.com/edgedb/edgedb-go/issues/153
=> Make optional type error more helpful

connutils.go
fixes https://github.com/edgedb/edgedb-go/issues/164
=> Implement `EDGEDB_INSECURE_DEV_MODE`

client.go, client_test.go, options.go, query_test.go, subtransaction_test.go, transactable.go, transaction.go, transaction_test.go, types_test.go, unix.go
fix https://github.com/edgedb/edgedb-go/issues/174
=> Remove RawTx() and rename RetryingTx() to Tx()

connect_test.go, connutils.go, connutils_test.go, credentials.go, error.go, main_test.go, options.go, sock.go, tutorial_test.go
fix https://github.com/edgedb/edgedb-go/issues/178
=> Update setting lookup from environment variables

client.go, client_test.go, connect.go, connutils.go, connutils_test.go, edgedb.go, fallthrough.go, internal/codecs/codecs.go, internal/codecs/datetime.go, internal/codecs/memory.go, internal/codecs/unmarshaler.go, internal/edgedbtypes/bool.go, internal/edgedbtypes/bytes.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/memory.go, internal/edgedbtypes/numbers.go, internal/edgedbtypes/numerics.go, internal/edgedbtypes/str.go, internal/edgedbtypes/uuid.go, internal/marshal/marshal.go, options.go, types.go, types_test.go
fix https://github.com/edgedb/edgedb-go/issues/186
=> Support protocol version 0.13

transactable.go
see also https://github.com/edgedb/edgedb-python/pull/243#discussion_r739337336
=> Fix reconnect condition

transactable.go
The `TransactionConflictError` class of errors is not only safe to
retry, it's _expected_ to be retried, so do that.
=> Retry statements on transaction conflict errors

reconnect.go
Connection retrying previously required 2 attempts before the WaitUntilAvailable timeout was considered. With this change a single connection attempt that takes longer than the WaitUntilAvailable timeout will not be attempted a second time.
=> Don't reconnect if WaitUntilAvailable has timedout

transaction_test.go
fix https://github.com/edgedb/edgedb-go/issues/189
=> Add a tx example

transactable.go
Serialization errors can be generated at commit time and should be retried.
=> Retry on TransactionError when attempting to commit

error.go
fixes https://github.com/edgedb/edgedb-go/issues/194
=> Retry on address not available

connutils.go, connutils_test.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/datetime_test.go
fixes https://github.com/edgedb/edgedb-go/issues/207
=> Add support for EDGEDB_WAIT_UNTIL_AVAILABLE

internal/codecs/codecs.go, internal/codecs/constants.go, internal/codecs/datetime.go, internal/codecs/unmarshaler.go, internal/edgedbtypes/bool_test.go, internal/edgedbtypes/bytes_test.go, internal/edgedbtypes/datetime.go, internal/edgedbtypes/datetime_test.go, internal/edgedbtypes/numbers_test.go, internal/edgedbtypes/numerics_test.go, internal/edgedbtypes/str_test.go, internal/edgedbtypes/uuid_test.go, internal/marshal/marshal.go, main_test.go, tutorial_test.go, types.go, types_test.go
fixes https://github.com/edgedb/edgedb-go/issues/230
=> Support cal::date_duration

README.md
fixes https://github.com/edgedb/edgedb-go/issues/238
=> Mention that go get should be run in a go module

internal/client/transaction.go, internal/client/transaction_test.go, internal/snc/rand.go
fixes https://github.com/edgedb/edgedb-go/issues/249
=> Correct protocol state passing in transactions

doc.go
fixes https://github.com/edgedb/edgedb-go/issues/209
=> Note in docs that edgedb.Duration is not time.Duration

internal/client/types_test.go, internal/codecs/json.go
fixes https://github.com/edgedb/edgedb-go/issues/253
=> Remove json format byte from returned optional json data

doc.go, internal/codecs/datetime.go, internal/codecs/datetime_test.go
fixes https://github.com/edgedb/edgedb-go/issues/257
=> Round time.Time to the nearest even microsecond

internal/client/connutils.go, internal/client/connutils_test.go
fixes https://github.com/edgedb/edgedb-go/issues/264
=> Update shared-client-testcases to latest

internal/client/edgedb.go
fixes https://github.com/edgedb/edgedb-go/issues/261
=> Handle error message in idle connections

internal/client/connutils.go, internal/client/connutils_test.go
Mirror https://github.com/edgedb/edgedb-python/pull/423
=> Update for rules of instance names

doc.go, internal/cmd/gendocs/rstprinter.go, rstdocs/index.rst
fixes https://github.com/edgedb/edgedb-go/issues/284
=> Document the $inline tag

internal/client/client.go, internal/client/granularflow2pX.go, internal/client/introspect.go, internal/client/query.go, internal/client/transaction.go, internal/codecs/noop.go
see also https://github.com/edgedb/edgedb/pull/6576
=> Don't parse transaction control commands

internal/client/connutils.go, internal/client/connutils_test.go, internal/client/credentials.go, internal/client/options.go, internal/client/utils.go
fixes https://github.com/edgedb/edgedb-go/issues/303
=> Add handling of `branch` option

internal/client/error.go, internal/client/granularflow1pX.go, internal/client/granularflow2pX.go, internal/client/scriptflow.go, internal/client/warning.go
The server may send a hint and position with a warning. Include this information when it is available.
=> Add hints to warnings

internal/client/connutils.go
Updates the shared client test cases.
=> Allow - and _ in org names

transaction_test.go
fixes https://github.com/geldata/gel-go/issues/335
=> Unskip malformed SQL query test

retry_test.go, transaction_test.go
fixes https://github.com/geldata/gel-go/issues/340
=> Add tests for Client.WithRetryOptions()

client_test.go
fixes https://github.com/geldata/gel-go/issues/294
=> Bring back session idle timeout test

client.go, client_examples_test.go, doc_test.go, example_test.go, options_test.go, pkgexamples_test.go
To view the rendered documentation run the following in a local checkout of this branch:
```bash
go run golang.org/x/pkgsite/cmd/pkgsite@latest
```
=> Add examples for client query methods

internal/client/credentials.go
1.4.1 is coming :)
Fixes https://github.com/geldata/gel-go/issues/388#issuecomment-3224745957 (again)
=> Fix database/branch null issue (again)
