- cache.go
- conn.go
- connect.go
- connect_test.go
- edgedb.go
- error.go
- granular_flow.go
- main_test.go
- options.go
- options_test.go
- pool.go
- pool_test.go
- poolconn.go
- poolconn_test.go
- query_test.go
- script_flow.go
- tutorial_test.go
This change adds:
- the ability to connect either a single connection or a pool
- the ability to acquire connections from a pool
- termination of all connections when a pool is closed
- configurable max and min connection counts
fixes https://github.com/edgedb/edgedb-go/issues/19
> implement optional pooling

- internal/codecs/array.go
- internal/codecs/array_test.go
fixes https://github.com/edgedb/edgedb-go/issues/34
Allow array arguments to be typed slices instead of requiring that they always be `[]interface{}`.
> Array args

- connect.go
- edgedb.go
- granular_flow.go
- internal/buff/testutils.go
- internal/buff/write.go
- internal/buff/write_test.go
- internal/codecs/array_test.go
- internal/codecs/base_scalar_test.go
- internal/codecs/named_tuple_test.go
- internal/codecs/tuple_test.go
- query_test.go
- script_flow.go
I added a test to start fixing https://github.com/edgedb/edgedb-go/issues/33 and discovered that it was already fixed, but the new test unearthed a bug caused by reusing the write buffer. This change creates a new write buffer for every payload sent to the server.
> fix stale write buffer bug

- granular_flow.go
- internal/codecs/array.go
- internal/codecs/array_test.go
- internal/codecs/base_scalar.go
- internal/codecs/base_scalar_test.go
- internal/codecs/codecs.go
- internal/codecs/named_tuple.go
- internal/codecs/named_tuple_test.go
- internal/codecs/object.go
- internal/codecs/object_test.go
- internal/codecs/set.go
- internal/codecs/set_test.go
- internal/codecs/tuple.go
- internal/codecs/tuple_test.go
- internal/marshal/marshal_test.go
- query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/54
This change enables decoding tuple elements to default types.
- Object and named tuples decode to map[string]interface{}
- tuples to []interface{}
- scalars to their respective types
- array & set to slice of whatever the element type decodes to
> support decoding non-scalar tuple elements

- borrow.go
- borrow_test.go
- conn.go
- edgedb.go
- generatederrors.go
- granular_flow.go
- internal/cmd/generr/errortype.go
- main_test.go
- pool.go
- pool_test.go
- poolconn.go
- transaction.go
- transaction_test.go
this is part of https://github.com/edgedb/edgedb-go/issues/32
- Interfaces are introduced to allow the most flexibility for future changes.
- Only the minimum transaction API is introduced to fulfill RFC1004 requirements. A fuller API if required is left for future work.
- Transaction is shortened to Tx because both [database/sql](https://golang.org/pkg/database/sql/#Tx) and [pgx](https://pkg.go.dev/github.com/jackc/pgx/v4#Tx) use this name and it seems to fit the Go naming paradigm of including the maximum information with the fewest characters.
- Interface names end in -er because that is the [go recommendation](https://golang.org/doc/effective_go.html#interface-names).
> add try transaction and retry

- granular_flow.go
- query_test.go
This change keeps reading server messages after ErrorResponse until ReadyForCommand is received. Previously it was possible for the client to stop reading messages when ErrorResponse was received.
> keep reading messages until ReadyForCommand

- options.go
- pool.go
- pool_test.go
fixes https://github.com/edgedb/edgedb-go/issues/66
This change uses a pool MinConns of 1 when MinConns is 0, and a MaxConns
of `max(4, runtime.NumCPU())` (arbitrarily borrowed from pgx) when
MaxConns is 0. Previously users were required to set MinConns and
MaxConns.
> add default min and max pool connections

- granular_flow.go
- internal/buff/read.go
- internal/buff/read_test.go
- internal/codecs/array.go
- internal/codecs/array_test.go
- internal/codecs/base_scalar.go
- internal/codecs/base_scalar_test.go
- internal/codecs/named_tuple.go
- internal/codecs/named_tuple_test.go
- internal/codecs/object.go
- internal/codecs/object_test.go
- internal/codecs/set.go
- internal/codecs/set_test.go
- internal/codecs/tuple.go
- internal/codecs/tuple_test.go
- tutorial_test.go
fixes https://github.com/edgedb/edgedb-go/issues/44
This change adds buff.Reader.PopSlice(n) which panics if the number of
bytes requested is more than the number of bytes available.
> assert data length

- granular_flow.go
- internal/codecs/array.go
- internal/codecs/array_test.go
- internal/codecs/base_scalar.go
- internal/codecs/base_scalar_test.go
- internal/codecs/codecs.go
- internal/codecs/named_tuple.go
- internal/codecs/named_tuple_test.go
- internal/codecs/object.go
- internal/codecs/object_test.go
- internal/codecs/path.go
- internal/codecs/set.go
- internal/codecs/set_test.go
- internal/codecs/tuple.go
- internal/codecs/tuple_test.go
- query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/5
This change adds the data structure field path to type miss-match error messages. An example error message would look like:
`expected mypackage.MyType.path.to.field to be int64, got int`
> improve type miss-match error messages

- .github/workflows/tests.yml
- README.md
The test strategy matrix for this project used to result in github running 20 checks which takes a long time. This change removes versions of go that are no longer [supported by google](https://golang.org/doc/devel/release.html#policy). Surveying several (~12) popular go packages all but one only runs tests against the two latest versions of go.
> remove old go versions from github workflows matrix

- internal/buff/read.go
- internal/buff/read_test.go
- internal/buff/write.go
- internal/buff/write_test.go
- internal/codecs/array.go
- internal/codecs/base_scalar.go
- internal/codecs/base_scalar_test.go
- internal/codecs/codecs.go
- internal/codecs/named_tuple.go
- internal/codecs/named_tuple_test.go
- internal/codecs/object.go
- internal/codecs/object_test.go
- internal/codecs/set.go
- internal/codecs/tuple.go
- internal/codecs/tuple_test.go
- internal/edgedbtypes/uuid.go
- internal/edgedbtypes/uuid_test.go
- query_test.go
- uuid.go
This change fixes a bug that made it impossible to use UUIDs as query arguments.
> fix uuid encoding

- connutils_test.go
- query_test.go
The server recently changed the string format for durations. This change updates tests to match the new format.
> fix broken tests

- doc.go
The import path never showed up in the documentation rendered for edgedb.com. This change adds it to the introductory example code.
> add import path to documentation

- doc.go
- granularflow.go
- internal/codecs/array.go
- internal/codecs/basescalar.go
- internal/codecs/basescalar_test.go
- internal/codecs/codecs.go
- internal/codecs/datetime.go
- internal/codecs/enum.go
- internal/codecs/namedtuple.go
- internal/codecs/object.go
- internal/codecs/set.go
- internal/codecs/tuple.go
- query_test.go
- types_test.go
fixes https://github.com/edgedb/edgedb-go/issues/117
This change makes tuples decode into structs the same way that named tuples and objects do rather than decoding into []interface{}. This makes the entire data structue's memory layout known from it's type which simplifies decoding significantly.
> change tuple mapping from []interface{} to struct

- internal/codecs/tuple.go
- query_test.go
fixes https://github.com/edgedb/edgedb-go/issues/112
This error now reads, "expected 3 arguments got 2".
> improve wrong number of arguments error

- connect.go
- error.go
- error_test.go
- granularflow.go
- query_test.go
- scriptflow.go
- types_test.go
fixes https://github.com/edgedb/edgedb-go/issues/116
A query snip-it with arrow and hint is introduced for syntax errors.
This implementation is very crude and likely to work poorly with characters outside of the ascii range because bytes are construed as characters. It also replaces tabs with spaces in the query to avoid misalignment when printed.
There doesn't seem to be a library in go similar to rust's [codespan](https://github.com/brendanzab/codespan) so the only option seems to be to roll our own.
`SELECT (foo (((1 2) 3)) 4)` produces
```
edgedb.EdgeQLSyntaxError: Unexpected token: <Token ICONST "2">
query:1:18
SELECT (foo (((1 2) 3)) 4)
^ It appears that a ',' is missing in a tuple before '2'
```
> add context to syntax errors

- conn.go
- edgedb.go
- generatederrors.go
- main_test.go
- options.go
- pool.go
- pool_test.go
- poolconn.go
- poolconn_test.go
- reconnect.go
- transaction.go
- transaction_test.go
fixes https://github.com/edgedb/edgedb-go/issues/122
- adds the following methods to Conn, Pool, and PoolConn
```go
// WithTxOptions returns a shallow copy of the pool
// with the TxOptions set to opts.
func (p Pool) WithTxOptions(opts TxOptions) *Pool
// WithRetryOptions returns a shallow copy of the pool
// with the RetryOptions set to opts.
func (p Pool) WithRetryOptions(opts RetryOptions) *Pool
```
- adds type TxOptions struct
```go
// WithIsolation returns a copy of the TxOptions
// with the isolation level set to i.
func (o TxOptions) WithIsolation(i IsolationLevel) TxOptions
// WithReadOnly returns a shallow copy of the pool
// with the transaction read only access mode set to r.
func (o TxOptions) WithReadOnly(r bool) TxOptions
// WithDeferrable returns a shallow copy of the pool …
```
> add transaction and retry options (RFC1004)

- edgedb.go
- fallthrough.go
fixes https://github.com/edgedb/edgedb-go/issues/126 which didn't have to do with options.
When running edgedb/edgedb-go against a development server (`edb server`) the server sent a [ParameterStatus message](https://www.edgedb.com/docs/internals/protocol/messages#parameterstatus) that the packaged server builds don't seem to send. The bit of code that is changed in this PR is not usually exercised because the tests don't have a way of triggering server initiated messages.
> remove unused connection attribute

- types_test.go
The test suite frequently runs out of memory on Windows in github actions.
> Reduce memory used by test suite

- connect_test.go
- connutils_test.go
- credentials_test.go
- internal/buff/write_test.go
- internal/edgedbtypes/uuid_test.go
- internal/marshal/marshal_test.go
- pool_test.go
- poolconn_test.go
- query_test.go
- reconnect_test.go
- transaction_test.go
- tutorial_test.go
- types_test.go
The old `assert.Nil()` assertion doesn't reliably show the error message
when an error does happen. `assert.NoError()` shows a more helpful
message in these scenarios.
> update nil error assertions

- connutils.go
It seems like `edgedb instance create` generates a TLS certificate for
127.0.0.1 and not localhost. The clients should assume 127.0.0.1 so that
they can connect using the credentials file which doesn't include a host
name.
> Change default host to 127.0.0.1

- README.md
- connect_test.go
- doc_test.go
- error_test.go
- granularflow.go
- internal/cardinality/cardinality.go
- pool.go
- pool_test.go
- poolconn.go
- poolconn_test.go
- query.go
- query_test.go
- reconnect.go
- transaction.go
- types_test.go
QuerySingJSON() is also added and QueryOneJSON() is also deprecated.
> Add QuerySingle() and deprecate QueryOne()

- .golangci.yml
- fallthrough.go
- internal/codecs/bool.go
- internal/codecs/numerics.go
- main_test.go
- poolconn.go
A couple of the linters that were configured were deprecated recently.
This change removes the depricated linters and replaces them with
golangci-lint's recomended replacements.
> update golangci-lint configuration

- pool.go
- poolconn.go
Remove the suggestion to use Tx methods to get a single connection.
> Reword deprecation messages

- borrow.go
- conn.go
- connect.go
- connect_test.go
- edgedb.go
- granularflow.go
- pool.go
- pool_test.go
- poolconn_test.go
- query.go
- query_test.go
- reconnect.go
- reconnect_test.go
- scriptflow.go
- subtransaction.go
- subtransaction_test.go
- transactable.go
- transaction.go
- transaction_test.go
- types_test.go
Public API changes:
- add `type Subtx struct`
- add `type SubtxBlock func(context.Context, *Subtx) error`
- add a `Subtx(context.Context, action SubtxBlock) error` method to `Tx` and `Subtx` structs
- rename `Action` to `TxBlock`
Internal Changes:
- Separated `type reconnectingConn struct` into `reconnectingConn`, `transactableConn`, and `borrowableConn`
- moved `txOpts` and `retryOpts` fields from `PoolConn` and `Conn` to `transactableConn`
- added helper function for running granular flow queries
- rename `baseConn.conn` to `baseConn.netConn`
- rename `PoolConn.conn` to `PoolConn.transactableConnactor` out `borrowableConn`
> implement subtransactions (RFC1004)

- options.go
- types.go
It is somewhat verbose to create an optional type variable and set its
value before using it.
```go
optional := edgedb.OptionalBool{}
optional.Set(true)
SomeStruct{
field: optional,
}
```
This change adds convenience functions for creating a new optional
value and setting its value.
```go
SomeStruct{
field: edgedb.NewOptionalBool(true),
}
```
related to https://github.com/edgedb/edgedb-go/issues/150
> Add convenience functions for optional types

- cache.go
- connect.go
- error.go
- granularflow.go
- internal/codecs/args.go
- internal/codecs/array.go
- internal/codecs/basescalar_test.go
- internal/codecs/bool.go
- internal/codecs/bytes.go
- internal/codecs/codecs.go
- internal/codecs/datetime.go
- internal/codecs/json.go
- internal/codecs/namedtuple.go
- internal/codecs/noop.go
- internal/codecs/numbers.go
- internal/codecs/numerics.go
- internal/codecs/object.go
- internal/codecs/set.go
- internal/codecs/str.go
- internal/codecs/tuple.go
- internal/codecs/unmarshaler.go
- internal/codecs/utils.go
- internal/codecs/uuid.go
- internal/descriptor/descriptor.go
- internal/marshal/marshal.go
- main_test.go
- query_test.go
- scriptflow.go
- types_test.go
fixes https://github.com/edgedb/edgedb-go/issues/151
- Add support for optional argument types. Previously all arguments were  treated as required even if they included the OPTIONAL key word. The  server version must be higher than 1-beta3 i.e. support protocol version 0.12 for this feature to work.
- Bump max protocol version to 0.12
- Make nil slices count as missing values for arrays.
- Fix bigint decoding bug that sums the decoded value with the value in  the memory that was decoded into.
- Fix query cache consistency bug by adding the out argument's type to  the cache key.
- Fix unmarshaler type checking. Previously any unmarshaler type could  be used with any descriptor type.
- Add handling CommandDataDescription sent in response to  OptimisticExecute.
> Support OPTIONAL argument types

- cache.go
- conn.go
- edgedb.go
- granularflow.go
- internal/header/header.go
- pool.go
- pool_test.go
- scriptflow.go
- transactable.go
fixes https://github.com/edgedb/edgedb-go/issues/158
Other minor changes:
- fixed bug in type ID caching. The key used to retrieve entries from the cache had different pieces of information from the key used to cache entries.
- fixed QueryOneJSON which was sending queries as format.Binary
> Retry readonly queries outside of transactions

- options.go
- pool.go
- pool_test.go
fixes https://github.com/edgedb/edgedb-go/issues/162
Use the server setting `suggested_pool_concurrency` as the default max concurrency if the user does not set the value explicitly.
> Suggested pool concurrency as default max pool size

- client.go
- client_test.go
- internal/edgedbtypes/numbers.go
- query.go
- query_test.go
- subtransaction.go
- transactable.go
- transaction.go
Make QuerySingle & QuerySingleJSON only return NoDataError on zero results if the out value's type is not an optional type.
fix https://github.com/edgedb/edgedb-go/issues/184
> Enable QuerySingle(JSON) lower cardinality assertion

- .github/workflows/tests.yml
- connect_test.go
- connutils.go
- connutils_test.go
- credentials.go
- main_test.go
- options.go
- tutorial_test.go
The client now supports `tls_ca` and `credentials` as direct options.  Also
spell `tls_ca_file` correctly as `tls_ca_file` in DSNs and move TLS
configuration options to a sub-struct in connection `Options` to future-proof it
for the possible additions of more options.
> Add support for non-file variants of `tls_ca_file` and `credentials_file`

- connutils.go
- credentials.go
`tls_ca` replaces the deprecated `tls_cert_data` for consistency with
granular connection options.
> Add support for `tls_ca` in `credentials.json`

- reconnect.go
Plenty of places are accessing `reconnectingConn.conn` directly, without copying it first and doing a `nil` check on it. A failing reconnect attempt is currently setting the `.conn` pointer to `nil`, making all these direct access call-sites panic from the nil pointer de-reference.
This PR is storing the new `.conn` value locally and only overwriting `reconnectingConn.conn` on the happy path.
> fix nil-ptr-deref caused by overwriting reconnectingConn.conn with nil

- error.go
I noticed out-of-bounds access on query lines when generating hints on the error code path.
This PR is adding a few bounds checks.
Unfortunately I did not keep the query for reproducing. Sorry about that.
> Add bounds checks on query position hint in error message generation

- internal/introspect/marshal.go
- internal/introspect/marshal_test.go
- query_test.go
Hi there!
Coming from mongodb/bson, I've adapted a pattern where I re-use field definitions for larger models by defining them once and composing them together using the `inline` tag. Like so:
<details>
<summary> Demo </summary>
---
This demo is informal and "Not a Submission.".
```go
type CommonTreeFields struct {
Id   primitive.ObjectID `json:"_id" bson:"_id"`
Name string             `json:"name" bson:"name"`
}
type FileRef struct {
CommonTreeFields `bson:"inline"`
Created time.Time `json:"created" bson:"created"`
Size    int64     `json:"size" bson:"size"`
}
type DeletedAtField struct {
DeletedAt time.Time `json:"deletedAt" bson:"deletedAt"`
}
type DeletedFileRef struct {
project.FileRef `bson:"inline"`
DeletedAtField  `bson:"inline"`
}
```
A `DeletedFileRef` has all the fields of a …
> Add support for traversing into structs using '$inline' struct tag

- error.go
- generatederrors.go
- internal/buff/read.go
- internal/buff/read_test.go
- internal/cmd/generr/main.go
- options.go
- transactable.go
panic-ing is kind of a bad practice in Golang as it requires all levels of goroutines to `recover` them. This is especially tricky when libraries (incl. edgedb-go) create them.
Instead of panic-ing it is better to just return an error or fail-safe.
This PR is refactoring all the direct `panic` invocations that are potentially reachable at runtime from unexpected server messages (e.g. unknown error message code, which tripped me up big) or other kinds of _harmless_ situations (missing flush of Buffer, unexpected error passed to retry rule).
Here is a break down of all the panics left un-touched:
<details>
```
./main_test.go-46-
./main_test.go-47-func executeOrPanic(command string) {
./main_test.go-48-      ctx := context.Background()
./main_test.go-49-      err := client.Execute(ctx, …
```
> refactor usage of panic: Only direct coding errors may trigger panics

- granularflow.go
On first glance it looked like this could yield empty `idPair`s. It required a few more reads (including the buff.Reader code) to understand that the loop cannot exit with `r.Err == nil` when the server did not sent all the messages yet -- with one remaining assumption: the server always sends `PrepareComplete` ahead of `ReadyForCommand`.
I think its simpler to just move the cache call right next to the population of the `idPair` :slightly_smiling_face: . WDYT?
_Side note: I've also fixed the typo in `cardinality` and dropped useless copying of already copied UUID bytes._
> Cache type ids immediately after reading them

- cmd/edgeql-go/gen.go
- cmd/edgeql-go/main.go
- cmd/edgeql-go/query.go
- cmd/edgeql-go/templates/file.template
- cmd/edgeql-go/templates/query.template
- cmd/edgeql-go/templates/struct.template
- cmd/edgeql-go/testdata/test-project2/object/select_link_prop_edgeql.go.assert
- cmd/edgeql-go/testdata/test-project2/object/select_object_edgeql.go.assert
- cmd/edgeql-go/testdata/test-project2/object/select_objects_edgeql.go.assert
- cmd/edgeql-go/testdata/test-project2/when_no_go_files_in_dir_dir_name_becomes_package_name/select_args_edgeql.go.assert
- cmd/edgeql-go/testdata/test-project2/when_no_go_files_in_dir_dir_name_becomes_package_name/subpkg/my_query_edgeql.go.assert
- cmd/edgeql-go/types.go
fixes https://github.com/edgedb/edgedb-go/issues/244
This also fixes a bug where generated range types had the wrong "optionality".
> Add named result types to generated code

- go.mod
- go.sum
- internal/client/connutils.go
- internal/client/connutils_test.go
- internal/client/options.go
Depends on https://github.com/edgedb/shared-client-testcases/pull/18
> Add cloud-credentials/secret_key parsing

- internal/client/client.go
fixes https://github.com/edgedb/edgedb-go/issues/259
This fixes a connection pooling bug that would permanently remove a connection from the pool if it's idle timeout expired. This effectively reduced the pools concurrency by one every time an idle timeout was reached.
> Correct connection pooling accounting

- internal/client/connutils.go
The old error said
```
%!w(<nil>): stopped searching for edgedb.toml at file system boundary "/home/fmoor"
```
The new error says
```
no edgedb.toml found: stopped searching for edgedb.toml at file system boundary "/home/fmoor"
```
> Improve no toml found because of fs boundary error

- internal/client/connutils.go
Nebula switched to doing this, and so the clients must follow.
> Lowercase instance and org name when computing instance DNS

- doc.go
This change is mostly to make `edgeql-go` more discoverable on https://pkg.go.dev/github.com/edgedb/edgedb-go
> Mention the code generator in the top level docs.

- cmd/edgeql-go/gen.go
- cmd/edgeql-go/templates/struct.template
- cmd/edgeql-go/testdata/mixedcaps/test-project2/object/select_object_edgeql.go.assert
- cmd/edgeql-go/testdata/mixedcaps/test-project2/scalar/select_array_edgeql.go.assert
- cmd/edgeql-go/testdata/mixedcaps/test-project2/scalar/select_scalars_edgeql.go.assert
- cmd/edgeql-go/testdata/mixedcaps/test-project2/tuple/select_tuple_edgeql.go.assert
- cmd/edgeql-go/testdata/no-args/test-project2/object/select_object_edgeql.go.assert
- cmd/edgeql-go/testdata/no-args/test-project2/scalar/select_array_edgeql.go.assert
- cmd/edgeql-go/testdata/no-args/test-project2/scalar/select_scalars_edgeql.go.assert
- cmd/edgeql-go/testdata/no-args/test-project2/tuple/select_tuple_edgeql.go.assert
- cmd/edgeql-go/types.go
This fixes a bug in the generator that didn't make optional structs optional.
Also, for generated code, this makes values in slices never be their optional variant.
> Use edgedb.Optional in generated optional structs

- export.go
- internal/client/executor.go
- rstdocs/api.rst
This PR introduces the `Executor` interface which exposes all querying functions that are common to both `Client` and `Tx`.
Example use-case:
```go
func CreateItem(db edgedb.Executor, name string) (item Item, err error) {
query := `select (insert Item { name := $0 }) { name };`
err = db.QuerySingle(context.Background(), query, &item, name)
return 
}
// Using Client
client, _ := edgedb.CreateClient(ctx, edgedb.Options{})
CreateItem(client, "Item name")
// Using Tx
client.Tx(context.Background(), func(ctx context.Context, tx *edgedb.Tx) error {
CreateItem(tx, "Item name")
// Transaction may then be rolled back, e.g. if this is a unit-test
return errors.New("Rollback")
})
```
> Expose a common interface between Client and Tx

- export.go
- internal/edgedbtypes/datetime.go
- internal/edgedbtypes/datetime_test.go
- rstdocs/types.rst
This is meant to improve usability of `Duration` values and better integrate with the Go ecosystem.
This also makes the unit (micro/nanoseconds) difference  between `Duration` and `time.Duration` more obvious, hopefully reducing the likelihood of introducing hard to detect bugs such as: 
```go
func ConvertDuration(d edgedb.Duration) time.Duration {
return time.Duration(int64(d)) 
// change from microseconds to nanoseconds representation is not taken care of, 
// and the compiler can not help to prevent this
}
> Add convenience functions to transform between edgedb.Duration and time.Duration

- internal/client/connect.go
- internal/client/granularflow0pX.go
- internal/client/granularflow1pX.go
- internal/client/granularflow2pX.go
- internal/client/scriptflow.go
Some server errors cause the client to also produce a network error. In these cases the client would report the network error but not the server error. This change makes the client report both errors, with the server error displayed first.
> Don't hide errors when multiple are encountered.

- .gitignore
- .vscode/settings.json
- internal/client/options.go
- internal/client/types_test.go
- internal/codecs/codecs.go
- internal/codecs/multirange.go
- internal/descriptor/descriptor.go
- internal/descriptor/descriptor_v2.go
- internal/edgedbtypes/datetime.go
- internal/edgedbtypes/multirange.go
- rstdocs/types.rst
Update descriptors.
Add multirange codec.
Add simple multi range test.
**NOTE**: I'll add more and better tests.
> Add multi range support

- export.go
- internal/client/cache.go
- internal/client/client.go
- internal/client/granularflow0pX.go
- internal/client/granularflow1pX.go
- internal/client/granularflow2pX.go
- internal/client/options.go
- internal/client/query.go
- internal/client/query_test.go
- internal/client/scriptflow.go
- internal/client/transactable.go
- internal/client/transaction.go
- internal/client/warning.go
- internal/cmd/export/names.txt
- internal/header/header.go
- rstdocs/api.rst
EdgeDB server recently added the ability to emit warnings. This change makes the client log them by default and adds a mechanism for users to define their own warning handler.
See [EdgeDB issue #7822](https://github.com/edgedb/edgedb/issues/7822)
> Add a warning system

- errors_gen.go
- internal/client/cache.go
- internal/client/client.go
- internal/client/client_test.go
- internal/client/connutils.go
- internal/client/constants.go
- internal/client/edgedb.go
- internal/client/errors_gen.go
- internal/client/fallthrough.go
- internal/client/granularflow2pX.go
- internal/client/introspect.go
- internal/client/language.go
- internal/client/query.go
- internal/client/scriptflow.go
- internal/client/testserver.go
- internal/client/transaction.go
- internal/client/transaction_test.go
- internal/client/warning.go
- internal/codecs/args.go
- internal/codecs/codecs.go
- internal/descriptor/descriptor.go
- internal/descriptor/descriptor_v2.go
- internal/descriptor/type_string.go
See JS implementation: https://github.com/edgedb/edgedb-js/pull/1131, and python: https://github.com/edgedb/edgedb-python/pull/534/files
> Add support for protocol v3 and add `QuerySQL` and `ExecuteSQL` client methods

- internal/client/client.go
- internal/client/constants.go
- internal/client/granularflow1pX.go
- internal/client/granularflow2pX.go
- internal/client/options.go
- internal/client/query.go
- internal/client/query_test.go
- internal/client/transactable.go
- internal/client/transaction.go
Adds a method to enable setting implicit limit and readonly options for queries. Needed for repl functionality in cloud: https://github.com/edgedb/nebula/pull/1874
Maybe todo:
> Add `WithQueryOptions` method

- client.go
- gelcfg/retryrule.go
- internal/client/transactable.go
- retry_test.go
- testserver_test.go
- transaction_test.go
- tutorial_test.go
Previously queries run with any method except for Execute() were automatically retried. Now queries run with Execute() are also retried.
Fixes https://github.com/geldata/gel-go/issues/333
> Retry queries run with Execute()

- .golangci.yml
- client.go
- client_examples_test.go
- connect_test.go
- doc_test.go
- example_test.go
- gelcfg/options.go
- gelcfg/queryoptions.go
- gelcfg/retryoptions.go
- gelcfg/retryrule.go
- gelcfg/txoptions.go
- geltypes/transaction.go
- internal/client/connutils.go
- internal/client/connutils_test.go
- options.go
- options_test.go
- pkgexamples_test.go
- tx_test.go
fixes https://github.com/geldata/gel-go/issues/288
To view the rendered documentation run the following in a local checkout of this branch:
```bash
go run golang.org/x/pkgsite/cmd/pkgsite@latest
```
> Add examples for Client.With*() methods

- client.go
- cmd/edgeql-go/endtoend_test.go
- doc.go
- example_test.go
- gelcfg/main_test.go
- gelcfg/options_test.go
- geltypes/example_test.go
- geltypes/main_test.go
- geltypes/numbers.go
- internal/testserver/server.go
This makes it so the examples are compiled and run with the test suite.
fixes https://github.com/geldata/gel-go/issues/362
To preview the generated docs run the following in the project root with this branch checked out.
```bash
go run golang.org/x/pkgsite/cmd/pkgsite@latest
```
> Move documentation examples into Example functions

- options_test.go
The stable and nightly server versions return different error messages which breaks this example. Don't validate the output until the new error message is in stable.
> Skip ExampleClient_WithTxOptions for now

- options_test.go
- testserver_test.go
Local dev has the option to reuse the same gel server for multiple test runs to save time. This is a fix for a couple issues in that workflow.
> Fix local dev issues when reusing the same gel server

- internal/client/connutils.go
- internal/client/connutils_test.go
- internal/client/credentials.go
- internal/client/credentials_test.go
The gel CLI recently started writing credentials files that use `null` to indicate that the default branch and/or database name should be used instead of specifying a value explicitly. This caused the following error in gel-go.
```
`database` must be a string
```
Closes #382
> Accept null branch & database in credentials files

- types_test.go
The nightly version of the server now uses [simple scoping][1]. This change in behavior made several queries used in tests both incorrect and enormously slow.
[1]: https://docs.geldata.com/reference/edgeql/path_resolution
> Make test queries simple scoping compatible

- internal/client/connutils.go
The `insecure` TLS mode could be used together with `TLSServerName`, which is useful if the Gel server is running in tenant host mode and uses SNI to route traffic to the correct tenant
> Allow TLSOptions.ServerName use with TLSOptions.SecurityMode
